import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import MegaMenu from "@/components/page/home/MegaMenu";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <div className='mx-8 lg:mx-20'>
          <MegaMenu />
          {children}
        </div>
      </body>
    </html>
  );
}
